### ISSUE TITLE
Provide simple `autoscaling_units` sample yaml

### ISSUE THREAD

**Issue by Layoric** [GeoscienceAustralia/amazonia#4]
Having the full `template.yaml` is great, but to encourage those to try it out, provide a simple example that can be copy/pasted straight from the README. 

Also show an abbreviated example of the output to give a sense of what this library can be used for! :+1: 

Eg:

``` yaml
#
# Example stack for Amazonia
#
​
stack_title: 'SimpleAMZ'
keypair: 'Simple'
autoscaling_units:
  -
    unit_title: 'appserver'
    hosted_zone_name: 'myhostedzone.com.'
    instance_type: 't2.micro'
    protocols:
     - 'HTTP'
    loadbalancerports:
     - '80'
    instanceports:
     - '80'
    path2ping: '/index.html'
    minsize: '1'
    maxsize: '1'
    health_check_grace_period: '300'
    health_check_type: 'ELB'
```
